.gitignore
index.html
styles.css

Started on a basic HTML and CSS layout.

style: creating basic HTML and CSS layout and design

---

index.html
index.js

Not sure if I used the best options in terms of DOM manipulation - it was first experience ever with this.
Not sure which format of the output number we prefer:
21.00 (that's what I did)
21 : 1
closes #24

feat: hex to ratio conversion

---

index.html
styles.css

Changed class name from `"row" ` to `"inputs-row"` on both `index.html` and `styles.css` files.
closes #26

refactor: changed class name to 'inputs-row'

---

index.html

A pass and fail svg icons was added to index.html

feat: adding pass fail icons

---

CODE_OF_CONDUCT.md

We don't have pr-template merged just yet.
But I guess checked all the stuuf that need to be checked.
closes #48

docs: created code-of-conduct

---

index.html

changes will remove the `for` attribute on both foreground and background input element.

fix: remove for attribute from inputs

---

README.md

fixed: typo in readme

---

README.md
index.html
index.js

Added dynamic copyright date using Javascript to target the HTML
closes #23

chore: dynamically add the year using JavaScript

---

README.md

docs: prerequisites section added

---

.github/pull_request_template.md

I added the PR template file to the codebase.
closes #21

chore: added a pr template

---

index.html
index.js

For now only works for cases when user managed to provide correct hex value.
@jdwilkin4 @Kernix13 
requesting you for review since you were discussing this at discord
closes #44

feat: dynamic change of colors in swatches

---

index.html
styles.css

Added some font styles to the text content.
closes #57 
Please, feel free to let me know if there is anything that needs to be changed​.
I also think the title and subtitle should both be wrapped in a `div`, and the `inputs-row` and `results-row` in another `div`.

style: applied some font styles

---

styles.css

added a  box shadow to the color swatches.
closes #60.

add box-shadow to color swatch closes #60

---

index.html
styles.css

All changes are related to the corresponding issue.
Fixes #69

fix: changes to heading structure

---

index.js

The RGB functionality gives the exact value.
I am still not certain about the RGBA functionality. Sometimes, the value is exact, and sometimes it is an approximate value. And some other times it's a wrong value (Maybe with dark transparent colors ..).
Fixes #25

Feat: implemented rgb and rgba functionality

---

CONTRIBUTING.md

Added the CONTRIBUTING.md file.
If there is anything that needs to be added or removed, please let me know.
Fixes #62

docs: add CONTRIBUTING.md file

---

README.md

Updated the How To Contribute section of the README file. 
Fixes #72

docs: add forking instructions to README file

---

index.html
index.js
styles.css

Added a message  which displays the supported formats when a users provides an unsupported format.
closes #(36)

Feat: user message for invalid input

---

index.html
styles.css

@sparkO7 couple of things:
I made box-shadow thingy a little bit thicker than 1 pixel.
I removed some CSS props because we are rewriting them anyway.
I made one placeholder to contain rgb value. That kinda gives idea that we can handle different formats here. Fancy stuff)
Also I have an idea for color of box-shadow thingy for future. We can change dynamically color for box-shadow depending on color in the swatch.
Also I noticed couple more weird things, but its out of the scope of this issue.
Fixes #84

fix: input's styling changed

---

styles.css

91 fix fout issue

---

README.md

Updated README.md description #100

---

index.html
styles.css

Added the AA+ and AAA+ text to index.html,  modifications to `.large` CSS selector and  refactor of index.html to include a `.levels`, `.level-label`, `.icons` and styling of these classes in style.css.
Fixes #86

Add AA+ and AAA+ text 

---

index.js

Remove console log statements 

---

README.md

Section added to inform beginners that they need to go through the process of becoming a contributor
#108 Update to how to contribute section in ReadMe
Fixes #108

docs: Update how to contribute section in README

---

styles.css

Fixed the color contrast ratio issues on the description and primary class to improve the lighthouse accessibility score from 95 to 100
Fixes #111

Fix color contrast ratio issues

---

styles.css

minor fix: css margin-bottom property

---

index.html
styles.css

- Added a check field selector, modified the height, width and border properties of the pass and fail selector
Fixes #85

refactor: Modifications on result row

---

index.html

Fixes #118 
- [ x] Chore items (this includes basic clean up of files, or updates to packages)
- [x ] I have a descriptive title for my PR
- [x ] I have linked this PR to the corresponding issue. [See how to do that here.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x ] I have run the project locally and reviewed the code changes
- [ x] My changes generate no new warnings

Chore - Update index.html #118

---

index.js

Removed all as requested
plus
removed relevant `if...else` blocks from `displayResult`
removed relevant regular expressions
Fixes #125

chore: hsla rgba functionality removed

---

package.json

Changes made as requested
Fixes #142

Chore: updated urls in package json

---

index.html
index.js
styles.css

Display pass if the graphics contrast ratio is good and fail if the graphics contrast ratio is poor.
Fixes #46

feat: dynamically add graphics content

---

styles.css

Changes improved responsiveness up to a dimension of 218 x 892.
Fixes #131.

Fix content overflow on smaller screens

---

index.js

Handling HSL invalid input errors
